#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pip
Version  : 21.2.3
Release  : 123
URL      : https://files.pythonhosted.org/packages/e1/63/7c0e553ae0513ebf1858f08030158ff5998324013e0ba4c2e1c00b85df79/pip-21.2.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/e1/63/7c0e553ae0513ebf1858f08030158ff5998324013e0ba4c2e1c00b85df79/pip-21.2.3.tar.gz
Summary  : The PyPA recommended tool for installing Python packages.
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause ISC LGPL-2.1 MIT MPL-2.0 Python-2.0
Requires: pip-bin = %{version}-%{release}
Requires: pip-license = %{version}-%{release}
Requires: pip-python = %{version}-%{release}
Requires: pip-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : setuptools-python

%description
pip - The Python Package Installer
==================================
.. image:: https://img.shields.io/pypi/v/pip.svg
:target: https://pypi.org/project/pip/

%package bin
Summary: bin components for the pip package.
Group: Binaries
Requires: pip-license = %{version}-%{release}

%description bin
bin components for the pip package.


%package license
Summary: license components for the pip package.
Group: Default

%description license
license components for the pip package.


%package python
Summary: python components for the pip package.
Group: Default
Requires: pip-python3 = %{version}-%{release}

%description python
python components for the pip package.


%package python3
Summary: python3 components for the pip package.
Group: Default
Requires: python3-core
Provides: pypi(pip)

%description python3
python3 components for the pip package.


%prep
%setup -q -n pip-21.2.3
cd %{_builddir}/pip-21.2.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1628263195
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pip
cp %{_builddir}/pip-21.2.3/LICENSE.txt %{buildroot}/usr/share/package-licenses/pip/1e5aed1c98e9df8eabbe2a271e641b4fc0cfb866
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/appdirs.LICENSE.txt %{buildroot}/usr/share/package-licenses/pip/a2e862db350c98bd10807b96ac2c1e80a894a45e
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/cachecontrol/LICENSE.txt %{buildroot}/usr/share/package-licenses/pip/04f8f19b0e946d9b4fa4704fbf010ddfd0d6ccc9
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/certifi/LICENSE %{buildroot}/usr/share/package-licenses/pip/79130bf30a84e5d08173ca68ae01ecd477ddba2a
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/chardet/LICENSE %{buildroot}/usr/share/package-licenses/pip/4eea9f6abed21a55d523472691c5391f373c7250
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/colorama/LICENSE.txt %{buildroot}/usr/share/package-licenses/pip/a8e1fddf0ff3d8bebb5cad56665a7022195ff1e9
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/distlib/LICENSE.txt %{buildroot}/usr/share/package-licenses/pip/3905e8ddbcb5ef371d6bc82ee03a03d4e7975ee8
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/distro.LICENSE %{buildroot}/usr/share/package-licenses/pip/6b8f5769b47147a271f7d5a808b802dcb44fab85
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/html5lib/LICENSE %{buildroot}/usr/share/package-licenses/pip/cf4c1b23db6057d8a48630ee35201015724b1431
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/idna/LICENSE.md %{buildroot}/usr/share/package-licenses/pip/603a23b855c2a22525d9de00347c2787070f3b10
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/msgpack/COPYING %{buildroot}/usr/share/package-licenses/pip/3b7725b241ea2278a971facd326ab790b141afe3
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/packaging/LICENSE.APACHE %{buildroot}/usr/share/package-licenses/pip/bd0b945d001aebc12dd7cdbf100427f1bc8d6957
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/packaging/LICENSE.BSD %{buildroot}/usr/share/package-licenses/pip/0156fc44e9a92e871fe58d650b392df3fc7c2dc3
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/pep517/LICENSE %{buildroot}/usr/share/package-licenses/pip/6ee2b3af25df70afdb567252d58c10a74b408108
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/pkg_resources/LICENSE %{buildroot}/usr/share/package-licenses/pip/fa4874ef0ea2a6734897fd1d3b162b4ac15b47e8
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/progress/LICENSE %{buildroot}/usr/share/package-licenses/pip/b737ea4018c9248b0c12a82b53a81904ace39884
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/pyparsing.LICENSE %{buildroot}/usr/share/package-licenses/pip/1d5d84d6fe1c735c23a6cb2449d5dd5353d778a5
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/requests/LICENSE %{buildroot}/usr/share/package-licenses/pip/89608a8f5632e1430c94fc5725a8aaea1a106ba6
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/resolvelib/LICENSE %{buildroot}/usr/share/package-licenses/pip/92fe3b597c2de31c7b1ee1931a092dcb8446e8aa
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/six.LICENSE %{buildroot}/usr/share/package-licenses/pip/5aa89b53a6e35810f63b69d01b463ef3c6576853
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/tenacity/LICENSE %{buildroot}/usr/share/package-licenses/pip/c8bc7df08db9dd3b39c2c2259a163a36cf2f6808
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/tomli/LICENSE %{buildroot}/usr/share/package-licenses/pip/a7047af892f123f0be8468a4f5dbb7aff9ef741c
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/urllib3/LICENSE.txt %{buildroot}/usr/share/package-licenses/pip/3ed480658fdb4f4cf165b969d292ce94cf57bf84
cp %{_builddir}/pip-21.2.3/src/pip/_vendor/webencodings/LICENSE %{buildroot}/usr/share/package-licenses/pip/5323b8f9eb88e014736bf859d605852e2a6b8c2c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
## Remove excluded files
rm -f %{buildroot}/usr/lib/python3.*/site-packages/pip/_vendor/distlib/t32.exe
rm -f %{buildroot}/usr/lib/python3.*/site-packages/pip/_vendor/distlib/w32.exe
rm -f %{buildroot}/usr/lib/python3.*/site-packages/pip/_vendor/distlib/w64.exe
rm -f %{buildroot}/usr/lib/python3.*/site-packages/pip/_vendor/distlib/t64.exe

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pip
/usr/bin/pip3
/usr/bin/pip3.9

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pip/0156fc44e9a92e871fe58d650b392df3fc7c2dc3
/usr/share/package-licenses/pip/04f8f19b0e946d9b4fa4704fbf010ddfd0d6ccc9
/usr/share/package-licenses/pip/1d5d84d6fe1c735c23a6cb2449d5dd5353d778a5
/usr/share/package-licenses/pip/1e5aed1c98e9df8eabbe2a271e641b4fc0cfb866
/usr/share/package-licenses/pip/3905e8ddbcb5ef371d6bc82ee03a03d4e7975ee8
/usr/share/package-licenses/pip/3b7725b241ea2278a971facd326ab790b141afe3
/usr/share/package-licenses/pip/3ed480658fdb4f4cf165b969d292ce94cf57bf84
/usr/share/package-licenses/pip/4eea9f6abed21a55d523472691c5391f373c7250
/usr/share/package-licenses/pip/5323b8f9eb88e014736bf859d605852e2a6b8c2c
/usr/share/package-licenses/pip/5aa89b53a6e35810f63b69d01b463ef3c6576853
/usr/share/package-licenses/pip/603a23b855c2a22525d9de00347c2787070f3b10
/usr/share/package-licenses/pip/6b8f5769b47147a271f7d5a808b802dcb44fab85
/usr/share/package-licenses/pip/6ee2b3af25df70afdb567252d58c10a74b408108
/usr/share/package-licenses/pip/79130bf30a84e5d08173ca68ae01ecd477ddba2a
/usr/share/package-licenses/pip/89608a8f5632e1430c94fc5725a8aaea1a106ba6
/usr/share/package-licenses/pip/92fe3b597c2de31c7b1ee1931a092dcb8446e8aa
/usr/share/package-licenses/pip/a2e862db350c98bd10807b96ac2c1e80a894a45e
/usr/share/package-licenses/pip/a7047af892f123f0be8468a4f5dbb7aff9ef741c
/usr/share/package-licenses/pip/a8e1fddf0ff3d8bebb5cad56665a7022195ff1e9
/usr/share/package-licenses/pip/b737ea4018c9248b0c12a82b53a81904ace39884
/usr/share/package-licenses/pip/bd0b945d001aebc12dd7cdbf100427f1bc8d6957
/usr/share/package-licenses/pip/c8bc7df08db9dd3b39c2c2259a163a36cf2f6808
/usr/share/package-licenses/pip/cf4c1b23db6057d8a48630ee35201015724b1431
/usr/share/package-licenses/pip/fa4874ef0ea2a6734897fd1d3b162b4ac15b47e8

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
