#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x6E3CBCE93372DCFA (donald@stufft.io)
#
Name     : pip
Version  : 9.0.1
Release  : 49
URL      : http://pypi.debian.net/pip/pip-9.0.1.tar.gz
Source0  : http://pypi.debian.net/pip/pip-9.0.1.tar.gz
Source99 : http://pypi.debian.net/pip/pip-9.0.1.tar.gz.asc
Summary  : The PyPA recommended tool for installing Python packages.
Group    : Development/Tools
License  : MIT
Requires: pip-bin
Requires: pip-legacypython
Requires: pip-python3
Requires: pip-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : py
BuildRequires : pytest
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : virtualenv

%description
===
        
        The `PyPA recommended

%package bin
Summary: bin components for the pip package.
Group: Binaries

%description bin
bin components for the pip package.


%package extras
Summary: extras components for the pip package.
Group: Default

%description extras
extras components for the pip package.


%package legacypython
Summary: legacypython components for the pip package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the pip package.


%package python
Summary: python components for the pip package.
Group: Default
Requires: pip-python3

%description python
python components for the pip package.


%package python3
Summary: python3 components for the pip package.
Group: Default
Requires: python3-core

%description python3
python3 components for the pip package.


%prep
%setup -q -n pip-9.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1518747064
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1518747064
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/pip2
%exclude /usr/bin/pip2.7
/usr/bin/pip
/usr/bin/pip3
/usr/bin/pip3.6

%files extras
%defattr(-,root,root,-)
/usr/bin/pip2
/usr/bin/pip2.7

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
